name: svg_shape_cliping
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  file_picker: ^5.3.3
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  http: ^1.1.0
  image: ^4.0.17
  path_drawing: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # assets:

